apiVersion: v1
kind: ConfigMap
metadata:
  name: nodeos-config
data:
{{ (.Files.Glob "files/nodeos-start.sh").AsConfig | indent 2 }}
{{ (.Files.Glob "files/config.ini").AsConfig | indent 2 }}
{{ (.Files.Glob "files/genesis.json").AsConfig | indent 2 }}
